name: vector
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  powersync: ^1.2.1
  supabase_flutter: ^2.5.4
  fpdart: ^1.2.0
  go_router: ^14.1.1
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  get_it: ^7.7.0
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  audioplayers: ^6.5.1
  vibration: ^3.1.5
  mapbox_maps_flutter: ^2.18.0
  geolocator: ^14.0.2
  turf: ^0.0.10
  flutter_riverpod: ^3.2.0
  sqflite: ^2.4.1
  path: ^1.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/audio/
